#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/operate ensure=absent force=true
puppet resource file /tmp/operate ensure=directory
cd /tmp/operate
git clone https://PrincessDem9nStud@github.com/6562515m-op-repo.git
cp -p /tmp/operate/index.html /var/www/html
